name: Cypress Tests
on: push
env:
  REGISTRY: ghcr.io
  WORKING_DIR: /root/residents-tracking-platform
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: Testing env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: run tests
        env:
          AWS_S3_ENDPOINT: ${{secrets.AWS_S3_ENDPOINT}}
          AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
          AWS_S3_KEY_ID: ${{secrets.AWS_S3_KEY_ID}}
          AWS_S3_ACCESS_KEY: ${{secrets.AWS_S3_ACCESS_KEY}}
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          DADATA_API_KEY: ${{secrets.DADATA_API_KEY}}
          DADATA_SECRET_KEY: ${{secrets.DADATA_SECRET_KEY}}
        run: |
          cp .env.test .env
          docker compose -f docker-compose.yml -f e2e/docker-compose.yml up --exit-code-from e2e
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          envs: WORKING_DIR
          script: |
            cd $WORKING_DIR
            git stash
            git pull
            docker compose build
            docker compose down
            docker compose up -d
            docker image prune -af