name: Cypress Tests
on: push
env:
  REGISTRY: ghcr.io
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: Testing env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run tests
        run: |
          touch .env
          docker compose -f docker-compose.yml -f e2e/docker-compose.yml up --exit-code-from e2e