name: Cypress Tests
on: push
env:
  REGISTRY: ghcr.io
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: Testing env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: run tests
        env:
          AWS_S3_ENDPOINT: ${{secrets.AWS_S3_ENDPOINT}}
          AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
          AWS_S3_KEY_ID: ${{secrets.AWS_S3_KEY_ID}}
          AWS_S3_ACCESS_KEY: ${{secrets.AWS_S3_ACCESS_KEY}}
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          DADATA_API_KEY: ${{env.DADATA_API_KEY}}
          DADATA_SECRET_KEY: ${{env.DADATA_SECRET_KEY}}
        run: |
          cp .env.test .env
          docker compose -f docker-compose.yml -f e2e/docker-compose.yml up --exit-code-from e2e