name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    environment: Testing env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run tests
        run: docker compose -f docker-compose.yml -f e2e/docker-compose.yml up --exit-code-from e2e